<?php
/**
 * Trive Fiskal API Library.
 *
 * @category  Trive
 * @package   Trive_Fiskal
 * @copyright 2017 Trive d.o.o (http://trive.digital)
 * @license   http://www.opensource.org/licenses/mit-license.php The MIT License
 * @link      http://trive.digital
 */
?>
<?php /* @var $block \Trive\Fiskal\Block\Adminhtml\Menu\Item */ ?>
<li>
    <a <?php /* @noEscape */ echo $block->serializeLinkAttributes() ?>>
        <?php echo $block->escapeHtml(__($block->getLabel())) ?>
    </a>
</li>
